// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGhI10GxTS1rsy6M-bWYZIlWXEkyHJdD4',
    appId: '1:181444641380:web:3004dd9ebbc728f49b5571',
    messagingSenderId: '181444641380',
    projectId: 'facebook-ba514',
    authDomain: 'facebook-ba514.firebaseapp.com',
    storageBucket: 'facebook-ba514.firebasestorage.app',
    measurementId: 'G-TS3PMG0F8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxiVhQCBUzDkJFfI25dx1XHMPx7R3chg',
    appId: '1:181444641380:android:30c47aeb53b858c89b5571',
    messagingSenderId: '181444641380',
    projectId: 'facebook-ba514',
    storageBucket: 'facebook-ba514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1cXdq2IdCm4JuOQ__5H0t42YvFwucN10',
    appId: '1:181444641380:ios:53f4ec441932e77c9b5571',
    messagingSenderId: '181444641380',
    projectId: 'facebook-ba514',
    storageBucket: 'facebook-ba514.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGhI10GxTS1rsy6M-bWYZIlWXEkyHJdD4',
    appId: '1:181444641380:web:4aedd61fbe6501be9b5571',
    messagingSenderId: '181444641380',
    projectId: 'facebook-ba514',
    authDomain: 'facebook-ba514.firebaseapp.com',
    storageBucket: 'facebook-ba514.firebasestorage.app',
    measurementId: 'G-9JVQCMBWXD',
  );
}
